### ISSUE TITLE
Add support for frontier genesis customizations

### ISSUE THREAD

**Issue by weezy20** [weezy20/pysubnet#10]
Add genesis customizations for `frontier` based nodes:

```toml
[frontier.evm.accounts]
"0x1000000000000000000000000000000000000001" = { balance = "0xd3c21bcecceda1000000", code = [
    0,
], nonce = "0x1", storage = {} }
"0x6be02d1d3665660d22ff9624b7be0551ee1ac91b" = { balance = "0xffffffffffffffffffffffffffffffff", code = [
], nonce = "0x0", storage = {} }
"0xd43593c715fdd31c61141abd04a99fd6822c8558" = { balance = "0xffffffffffffffffffffffffffffffff", code = [
], nonce = "0x0", storage = {} }

[frontier.evmChainId]
chainId = 42
```

Most often, `pallet-evm` is configured to use `pallet-balances` as it's currency type so these balances will also reflect on `pallet-balances` storage. 
Also note that you can also still specify `balances` keys for each `[[node]]` however those keys are generated by pysubnet so you can't specify keys with balances. 

Future support should include a additional `[balances]` field for the config file so that we have one place where you can insert into `pallet-balances` storage. 

Besides that, setting `nonce`, `storage`, `code` could prove useful to some developers and it's easy to support that in the same PR.
